apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  selector:
    app: techtrends
  ports:
  - port: {{ .Values.service.port }}    
    {{ if .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    {{ else }}
    targetPort: {{ .Values.service.port }}
    {{ end }}
    protocol: {{ .Values.service.protocol }}
  type: {{ .Values.service.type }}
