apiVersion: apps/v1
kind: Deployment

metadata:
 name: techtrends
 namespace: sandbox
 labels:
  app: techtrends

spec:
 replicas: 1
 selector:
  matchLabels:
   app: techtrends
 template:
  metadata:
   labels:
    app: techtrends
  spec:
   containers:
      - name: tech-trends
        image: tech-trends:latest
        imagePullPolicy: IfNotPresent
        resources:
         requests:
          cpu: 250m
          memory: 64Mi
         limits:
          memory: 128Mi
          cpu: 500m
        ports:
        - containerPort: 3111
        livenessProbe:
         httpGet:
          port: 3111
          path: /healthz
        readinessProbe:
         httpGet:
          port: 3111
          path: /healthz
