name: TechTrends - Package with Docker

on:
 push:
  branches: [udacity-tech-trends]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   -
    name: checkout
    uses: actions/checkout@v1
   -
    name: Set up QEMU
    uses: actions/setup-qeum-action@v2
   -
    name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1
   -
    name: Login to Docker Hub
    uses: docker/login-action@v1
    with:
     username: ${{ secrets.DOCKERHUB_USERNAME}}
     password: ${{ secrets.DOCKERHUB_TOKEN}}
   -
    name: Doocker Images Build and Push 
    uses: docker/build-push-action@v2
    with:
     context: .
     filename: ./Dockerfile
     platform: linux/amd64, linux/arm64
     push: true
     tags: "jayjs/tech-trends:latest"
    

