name: TechTrends - Package with Docker 

on:
 push:
   branches: 
     - udacity-tech-trends-proj
     - main
 pull_request:
   branches: 
     - udacity-tech-trends-proj
     - main

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   -
    name: checkout
    uses: actions/checkout@v1
   -
    name: Docker meta
    id: meta
    uses: docker/metadata-action@v4
    with:
     images: |
      https://hub.docker.com/repository/docker/jayjs/tech-trends
     tags: |
      type=schedule
      type=semver,pattern={{version}}
      type=semver,pattern={{major}}.{{minor}}
      type=semver,pattern={{major}}
      type=ref,event=branch
      type=ref,event=pr
      type=sha
   -
    name: Set up QEMU
    uses: docker/setup-qemu-action@v2
   -
    name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1
   -
    name: Login to Docker Hub
    uses: docker/login-action@v1
    with:
     username: ${{ secrets.DOCKERHUB_USERNAME}}
     password: ${{ secrets.DOCKERHUB_TOKEN}}
   -
    name: Doocker Images Build and Push 
    uses: docker/build-push-action@v2
    with:
     context: ./project/techtrends
     filename: ./Dockerfile
     platform: linux/amd64, linux/arm64
     push: true
     #tags: "jayjs/tech-trends:latest"
     tags: ${{ steps.meta.outputs.tags }}
    

